### ISSUE TITLE
compute ground state

### ISSUE THREAD

**Issue by pengfzhou** [QuEraComputing/GenericTensorNetworks.jl#41]
from my point of view, computing ground state with gradients method such as backpropagation will cost much memory, which need cache every imtermediate contraction tensor.  Also I am not familar with the details of  the gradient method with Fowarddiff or Nilang. maybe they will save memory and compute faster.  Here I just offer another method presented in below figure<img width="568" alt="image" src="https://user-images.githubusercontent.com/32509736/165751380-6579ecb1-0a73-4d90-a83a-bd5d0d495952.png">
<img width="568" alt="image" src="https://user-images.githubusercontent.com/32509736/165753167-e4c6626a-11b0-4f89-a109-09866c2f2fea.png">
Obviously, we only need to store the index when doing max operation, for  a spin glass problem on a 3-regular graph with $n$ vertex corresponding to a  tensornetwork  with $n$ index and $3/2*n$ tensors;  if we want to get the ground state, we at most store  $n$ index tensor from contraction operation with max (when some contraction only involve sum operation, it won't creat index tensor , when some indices are merged, we will store indermidate index tensor less that $n$ )
Above figure is a very naive contraction order, because only involving 4 index, we can write the contraction result into formula and index tensor also can be written simply. Also I am not sure whether the method has advantage and whether you have implemented this method, Even maybe  this method is conncted with gradient method.  Look forward to your answer!

**Comment by GiggleLiu** [comment]
Hi, @pengfzhou thanks for openning this issue to share your idea, I appreciate it! If I understand correctly, your method is equivalent to back-propagation because you also need extra memory to store intermediate configurations, wrong?

 Actually, the default method for obtaining single solution in `GenericTensorNetworks` is not backpropagation, it is an algebra called `ConfigSampler`: https://queracomputing.github.io/GenericTensorNetworks.jl/dev/ref/#GenericTensorNetworks.ConfigSampler 
The `SingleConfigMax(; bounded=true)` calls the back-propagation method, it can take the advantage of tropical GEMM: https://queracomputing.github.io/GenericTensorNetworks.jl/dev/performancetips/#GEMM-for-Tropical-numbers. It is slightly faster in general, while being more memory inefficient. The following is a benchmark in our paper
![image](https://user-images.githubusercontent.com/6257240/165788642-a2565e37-72ac-4111-9531-184f92cb10c1.png)

where Fig (d), Single MIS (P1+S1, CPU) and Single MIS (T+bounding, CPU) shows the differences.
Here, bounding is another word of saying back-propagation.

The paper is coming out soon!

**Comment by GiggleLiu** [comment]
Check our paper: https://arxiv.org/abs/2205.03718
